# Generated by Django 5.0.1 on 2024-03-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_remove_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
