# Generated by Django 5.0.1 on 2024-03-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_webinars', to='webinars.customuser'),
        ),
    ]
