# Generated by Django 5.0.1 on 2024-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0006_alter_webinar_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='registrations',
            field=models.IntegerField(default=0),
        ),
    ]
