# Generated by Django 5.0.1 on 2024-03-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0007_webinar_registrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
