# Generated by Django 5.0.1 on 2024-04-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='link',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
