# Generated by Django 5.0.1 on 2024-04-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0012_alter_webinar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='link',
            field=models.URLField(default='http://www.google.com', max_length=100),
        ),
    ]
