# Generated by Django 5.0.1 on 2024-04-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0014_remove_webinar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='link',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
