# Generated by Django 5.0.1 on 2024-04-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0017_webinar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
